inherit_from: .rubocop_todo.yml

# rubocop関連のgemも使ってチェック
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.1
  # 以下のファイルは対象から外す
  Exclude:
    - db/migrate/**/*
    - db/schema.rb
    - tmp/**/*
    - vendor/**/*

# --------Style--------
# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

# Classの継承の記述でcompact形式を許可
Style/ClassAndModuleChildren:
  Enabled: false

# --------Metrics--------
# １行の文字数制限
# Metrics/LineLength:
#   Max: 120