# rubocop関連のgemも使ってチェック
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.1
  # 新規に追加されたルールも適用する
  NewCops: enable
  # 以下のファイルは対象から外す
  Exclude:
    - db/migrate/**/*
    - db/schema.rb
    - tmp/**/*
    - vendor/**/*
    - bin/**/*

# --------Layout--------
# １行の長さ
Layout/LineLength:
  Exclude:
  - config/initializers/application_controller_renderer.rb

# --------Lint--------
# superで継承だけしているメソッドを許容
Lint/UselessMethodDefinition:
  Exclude:
    - app/controllers/user/registrations_controller.rb
    - app/controllers/user/sessions_controller.rb

# --------Metrics--------
# rspec内の１ブロックあたりの行数はチェックしない
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# AbcSizeチェックの許容上限値
Metrics/AbcSize:
  Max: 20

# --------RSpec--------
# contextが'when','with','without'で始まらなくてもよい
RSpec/ContextWording:
  Enabled: false

# itの中の最大行数
RSpec/ExampleLength:
  Max: 10

# --------Style--------
# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

# Classの継承の記述でcompact形式を許可
Style/ClassAndModuleChildren:
  Enabled: false

# ドキュメント用のコメントを付けなくてもよい
Style/Documentation:
  Enabled: false

# メソッド呼び出し時に"self."と付けるのを許可(特にmodel内ではその方がわかりやすい)
Style/RedundantSelf:
  Enabled: false
