default: &default
  adapter: mysql2
  charset: utf8mb4
  collation: utf8mb4_general_ci
  encoding: utf8mb4
  password: ''
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>

development:
  <<: *default
  database: myapp_development
  # host: db
  host: localhost

test:
  <<: *default
  database: myapp_test
  # host: <%= ENV.fetch("DB_HOST_TEST") { 'db' } %>
  host: <%= ENV.fetch("DB_HOST_TEST") { 'localhost' } %>

production:
  <<: *default
  database: myapp_production
  host: <%= ENV['DB_HOST_PRODUCTION'] %>
  password: <%= ENV['DB_PASSWORD'] %>
